package bedrockDragon.network.raknet.protocol.game.world

import bedrockDragon.network.raknet.protocol.game.MinecraftPacketConstants
import bedrockDragon.network.raknet.protocol.game.PacketPayload

class StructureTemplateDataExportResponsePacket: PacketPayload(MinecraftPacketConstants.STRUCTURE_TEMPLATE_DATA_EXPORT_RESPONSE) {
}